feat(community): add foss united delhi
asetalias/asetalias.github.io pull request #315
Opened 2024-02-20 17:09 UTC by X3nyy

2024-02-20 17:31 UTC, Maniktherana commented
looks kinda blurry, I suggest dropping `${styles.outline}`
<img width="376" alt="Screenshot 2024-02-20 at 10 59 12 PM" src="https://github.com/asetalias/asetalias.github.io/assets/14011425/e9a1a1ee-4021-48cd-9e0b-fa050cc8571e">

2024-02-20 17:34 UTC, Maniktherana requested changes

2024-02-20 17:34 UTC, Maniktherana commented on src/components/Community/Community.jsx
> +            className={`${styles.community__chapter} ${styles.outline}`}
```suggestion
            className={`${styles.community__chapter}`}
```
this should remove the blur

2024-02-21 14:37 UTC, chanu4321 commented
LGTM

2024-02-21 14:37 UTC, merged